### ISSUE TITLE
Aufgabenstellung prüfen und ggf. ergänzen

### ISSUE THREAD

**Issue by holgerzer** [huichen5796/2022-projektarbeit-hui-chen#6]
Hi Hui!

Ich habe eine erste Version der Aufgabenstellung fertig und ins Git geladen. Du kannst schon mal drüber schauen und Anmerkungen machen, ob noch was fehlt.

Gruß,
Holger

**Comment by huichen5796** [comment]
Moin! habe drüber schauen, alles toll aber mein Nachname ist Chen nicht Shen, XD. Matrikelnummer ist 10048521.

**Comment by holgerzer** [comment]
Habe alles angepasst.
